### DISCUSSION TITLE
What is the correct config to allow a tor hidden service to reach the dockerized mempool?

### DISCUSSION THREAD

**Discussion by SeaSquared24** [mempool/mempool#3662] [Q&A]
I used Ministry of Nodes's guide to build mempool but I am attaching all of my services as tor hidden services rather than using ssl and domain names. In his tutorial, he only shows using mempool from the local IP anyways. So this is what I've got so far. 

```
version: "3.7"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 4080:8080
  api:
    environment:
      SOCKS5PROXY_ENABLED: "true"
      SOCKS5PROXY_HOST: "127.0.0.1"
      SOCKS5PROXY_PORT: "9050"
      SOCKS5PROXY_USERNAME: ""
      SOCKS5PROXY_PASSWORD: ""
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "192.168.0.242"
      ELECTRUM_PORT: "50002"
      ELECTRUM_TLS_ENABLED: "true"
      CORE_RPC_HOST: "192.168.0.242"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "[redacted]"
      CORE_RPC_PASSWORD: "[redacted]"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache
  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
  ```

The tor hidden service lines in /etc/tor/torrc look like this:

```
HiddenServiceDir /var/lib/tor/mempool
HiddenServicePort 4080 127.0.0.1:4080
```
