### ISSUE TITLE
Cannot connect to a locally hoisted Bitcoin-Core

### ISSUE THREAD

**Issue by TravelingTechGuy** [mempool/mempool#3854]
### Description

Mempool and `bitcoind` run on the same machine, under the same user. Despite providing the right parameters, and despite verification that the RPC service is up and accessible, I get `ECONNREFUSED` errors.

#### Version

v2.5.0

### Steps to reproduce

1. Install Bitcoin core
2. Provide the following `bitcoin.conf` file:
```
txindex=1
server=1
rpcallowip=0.0.0.0/0
rpcport=8332
rpcuser=mempool
rpcpassword=mempool
```
3. Provide the following `docker-compose.yml` file:
```
version: "3.7"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 8080:8080
  api:
    environment:
      MEMPOOL_BACKEND: "none"
      CORE_RPC_HOST: "127.0.0.1"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "mempool"
      CORE_RPC_PASSWORD: "mempool"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache
  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql
```
4. Run `bitcoind -daemon` (verifying it runs the right conf file)
5. Test RPC successfully using:
```
curl --user "mempool:mempool" --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblockchaininfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
```
6. Run Mempool (`docker compose up` in `mempool/docker` folder)

### Expected behaviour

Mempool successfully connects to local node.

### Actual behaviour

This message appears every 40 seconds:
```
docker-api-1  | Jun 12 19:23:10 [111] WARN: Exception in runMainUpdateLoop(). Retrying in 40 sec. Reason: connect ECONNREFUSED 127.0.0.1:8332. Stack trace: Error: connect ECONNREFUSED 127.0.0.1:8332
```

#### Device or machine

Raspberry Pi 4, 8GB memory, 1TB HD, running Debian 10 (Buster)

#### Additional info

N/A
