### ISSUE TITLE
Docker-compose mysql errors

### ISSUE THREAD

**Issue by michelem09** [mempool/mempool#494]
I'm trying to use the docker version with docker-compose (https://github.com/mempool/mempool/tree/master/docker) but when I try it I got this:

```
Creating network "docker-mempool_default" with the default driver
Creating docker-mempool_web_1 ... done
Creating docker-mempool_db_1  ... done
Creating docker-mempool_api_1 ... done
Attaching to docker-mempool_api_1, docker-mempool_db_1, docker-mempool_web_1
db_1   | 2021-05-05 09:46:42+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+maria~focal started.
api_1  | wait-for-it.sh: waiting 720 seconds for db:3306
db_1   | 2021-05-05 09:46:42+00:00 [Note] [Entrypoint]: Initializing database files
db_1   | 2021-05-05  9:46:42 0 [Warning] Can't create test file /var/lib/mysql/2dd2ad629369.lower-test
db_1   | 2021-05-05  9:46:42 0 [ERROR] mysqld: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 13 "Permission denied")
db_1   | 2021-05-05  9:46:42 0 [ERROR] mysqld: Got error 'Can't create file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
db_1   | 2021-05-05  9:46:42 0 [ERROR] Plugin 'Aria' init function returned error.
db_1   | 2021-05-05  9:46:42 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
db_1   | 2021-05-05  9:46:42 0 [ERROR] InnoDB: Operating system error number 13 in a file operation.
db_1   | 2021-05-05  9:46:42 0 [ERROR] InnoDB: The error means mysqld does not have the access rights to the directory.
db_1   | 2021-05-05  9:46:42 0 [ERROR] InnoDB: Operating system error number 13 in a file operation.
db_1   | 2021-05-05  9:46:42 0 [ERROR] InnoDB: The error means mysqld does not have the access rights to the directory.
db_1   | 2021-05-05  9:46:42 0 [ERROR] InnoDB: Cannot open datafile './ibdata1'
db_1   | 2021-05-05  9:46:42 0 [ERROR] InnoDB: Could not open or create the system tablespace. If you tried to add new data files to the system tablespace, and it failed here, you should now edit innodb_data_file_path in my.cnf back to what it was, and remove the new ibdata files InnoDB created in this failed attempt. InnoDB only wrote those files full of zeros, but did not yet use them in any way. But be careful: do not remove old data files which contain your precious data!
db_1   | 2021-05-05  9:46:42 0 [ERROR] InnoDB: Database creation was aborted with error Cannot open a file. You may need to delete the ibdata1 file before trying to start up again.
db_1   | 2021-05-05  9:46:42 0 [ERROR] Plugin 'InnoDB' init function returned error.
db_1   | 2021-05-05  9:46:42 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1   | 2021-05-05  9:46:42 0 [ERROR] Failed to initialize plugins.
db_1   | 2021-05-05  9:46:42 0 [ERROR] Aborting
db_1   | 
db_1   | Installation of system tables failed!  Examine the logs in
db_1   | /var/lib/mysql/ for more information.
db_1   | 
db_1   | The problem could be conflicting information in an external
db_1   | my.cnf files. You can ignore these by doing:
db_1   | 
db_1   |     shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf
db_1   | 
db_1   | You can also try to start the mysqld daemon with:
db_1   | 
db_1   |     shell> /usr/sbin/mysqld --skip-grant-tables --general-log &
db_1   | 
db_1   | and use the command line tool /usr/bin/mysql
db_1   | to connect to the mysql database and look at the grant tables:
db_1   | 
db_1   |     shell> /usr/bin/mysql -u root mysql
db_1   |     mysql> show tables;
db_1   | 
db_1   | Try 'mysqld --help' if you have problems with paths.  Using
db_1   | --general-log gives you a log in /var/lib/mysql/ that may be helpful.
db_1   | 
db_1   | The latest information about mysql_install_db is available at
db_1   | https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
db_1   | You can find the latest source at https://downloads.mariadb.org and
db_1   | the maria-discuss email list at https://launchpad.net/~maria-discuss
db_1   | 
db_1   | Please check all of the above before submitting a bug report
db_1   | at https://mariadb.org/jira
db_1   | 
```

Can't find the problem, any ideas?

**Comment by wiz** [comment]
The relevant error line in your log is this
```
db_1   | 2021-05-05  9:46:42 0 [ERROR] mysqld: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 13 "Permission denied")
```
Can you post your entire docker-compose file? Seems like you are running mysql with the incorrect permissions maybe.

**Comment by michelem09** [comment]
I just copied the example in the page and created the relative directory as explained:

```
version: "3.7"

services:
  web:
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 80:8080
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
  api:
    image: mempool/backend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache
    environment:
      RPC_HOST: "127.0.0.1"
      RPC_PORT: "8332"
      RPC_USER: "mempool"
      RPC_PASS: "mempool"
      ELECTRUM_HOST: "127.0.0.1"
      ELECTRUM_PORT: "50002"
      ELECTRUM_TLS: "false"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASS: "mempool"
      BACKEND_MAINNET_HTTP_PORT: "8999"
      CACHE_DIR: "/backend/cache"
      MEMPOOL_CLEAR_PROTECTION_MINUTES: "20"
  db:
    image: mariadb:10.5.8
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/db-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
```
