### ISSUE TITLE
Fee histogram and "incoming transactions" graph do not display at all

### ISSUE THREAD

**Issue by maltokyo** [mempool/mempool#504]
### Description

Official mempool.space site shows two graphs that do not display on my own installation.

#### Version

See docker-compose file below for all images and versions used.

### Steps to reproduce

Run as per below docker-compose file.

### Expected behaviour

Graphs show like the main official site - mempool.space (official site) looks like this:
![image](https://user-images.githubusercontent.com/1388507/117548606-2cb95c80-b036-11eb-99f9-3a523d946523.png)

### Actual behaviour

As above, graphs dont show - My version looks like this:
![image](https://user-images.githubusercontent.com/1388507/117548611-3642c480-b036-11eb-80b3-d85c83ea6b24.png)

#### Device or machine

Debian 10, with latest version of docker.

#### Additional info

docker-compose.yml file with all versions and images used.

```yml
version: "3.7"

x-logging:
  &default-logging
  driver: journald


services:
  mempool_web:
    container_name: mempool_web
    image: mempool/frontend:v2.1.2@sha256:69fefe55dc1eb4c8373c32d57362df7eeb672fc591d55033d68ae79355274dcc
    init: true
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for mempool_db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    # ports:  # dont need these behind RP
    #   - 3006:3006
    environment:
      FRONTEND_HTTP_PORT: "80"
      BACKEND_MAINNET_HTTP_HOST: "mempool_api"

  mempool_api:
    container_name: mempool_api
    image: mempool/backend:v2.1.2@sha256:58394cb35aad82b95ab2496fd4a6d3c983a712a1003454d94b0a53197d306f6d
    init: true
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh mempool_db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - mempoolapidir:/backend/cache
    environment:
      RPC_HOST: "bitcoind"
      RPC_PORT: "43782"
      RPC_USER: "REDACTED"
      RPC_PASS: "REDACTED"
      ELECTRS_HOST: "electrumx"
      ELECTRS_PORT: "50002"
      MYSQL_HOST: "mempool_db"
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASS: "REDACTED"
      BACKEND_MAINNET_HTTP_PORT: "8999"
      CACHE_DIR: "/backend/cache/"
      MEMPOOL_CLEAR_PROTECTION_MINUTES: "20"

  mempool_db:
    container_name: mempool_db
    image: mariadb:10.5.8@sha256:8040983db146f729749081c6b216a19d52e0973134e2e34c0b4fd87f48bc15b0
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - mempooldbdir:/var/lib/mysql
      - mempooldbscriptsdir:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "REDACTED"
      MYSQL_ROOT_PASSWORD: "REDACTED"

# use docker native volumes
volumes:
  mempoolapidir:
  mempooldbdir:
  mempooldbscriptsdir:
```
