### ISSUE TITLE
search by address can't work on custome signet 

### ISSUE THREAD

**Issue by Yihen-Liu** [mempool/mempool#5181]
#### Description
I setup a custome bitcoin signet network with three mining nodes. and set the mempool backend ENV as follow:
```
  mempool-api:
    image: mempool/backend:v3.0.0-dev8
    environment:
      - CORE_RPC_HOST=knots
      - CORE_RPC_PASSWORD=satoshi@password
      - CORE_RPC_PORT=38332
      - CORE_RPC_USERNAME=satoshi
      - DATABASE_DATABASE=mempool
      - DATABASE_ENABLED=true
      - DATABASE_HOST=mariadb
      - DATABASE_PASSWORD=mempool
      - DATABASE_USERNAME=mempool
      - ELECTRUM_HOST=electrs
      - ELECTRUM_PORT=60601
      - ELECTRUM_TLS_ENABLED=false
      - MEMPOOL_BACKEND=electrum
      - MEMPOOL_NETWORK=signet
      - STATISTICS_ENABLED=false
      - MEMPOOL_INDEXING_BLOCKS_AMOUNT=-1
      - MEMPOOL_AUTOMATIC_BLOCK_REINDEXING=true
      - MEMPOOL_BLOCKS_SUMMARIES_INDEXING=true
      - MEMPOOL_GOGGLES_INDEXING=true
      - MEMPOOL_AUDIT=true
      - MEMPOOL_CPFP_INDEXING=true
      - MEMPOOL_ENABLED=true
      - MEMPOOL_OFFICIAL=true
      - MEMPOOL_API_URL_PREFIX=/api/v1/
    restart: on-failure
```
when I past a testnet/signet address on search bar, it does not work. show as follows:
![image](https://github.com/mempool/mempool/assets/7480459/e3623468-930b-4ea6-a3b1-f2cd879080d6)

#### Version

v3.0.0-dev [[3a8c46bb](https://github.com/mempool/mempool/commit/3a8c46bb)]

#### Device or machine

macbook-pro & chrome

#### Additional info

I deploy the website on myself Domain Name： signet.sathub.io， you can reproduce it by paste any testnet/signet ADDRESS.
